variables:
    TEST_NAME: registry.gitlab.com/nabillefi/whertoeat:$CI_COMMIT_REF_NAME

stages:
    - build
    - run
    - deploy

build_docker_images:
    stage: build
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
        - docker build -t $TEST_NAME .
        - docker push $TEST_NAME
    tags:
        - build
run_docker_images:
    stage: run
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
        - docker pull $TEST_NAME
        - docker kill $(docker ps -q) || true
        - docker rm $(docker ps -a -q) || true
        - docker run -dt -p 8090:80 --name gitlabCICDContainer $TEST_NAME
    tags:
        - run

